### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by ConnorDoesDev** [VoltrexMaster/string-toolkit#7]
I know, this is a not-so-cool place to submit feedback, but yeah.
I love this! I firstly thought I won't use this, but woah! It's great, I implemented the emojify method in my D.JS bot and it works perfectly, good job!

**Comment by VoltrexMaster** [comment]
> I know, this is a not-so-cool place to submit feedback, but yeah.
> I love this! I firstly thought I won't use this, but woah! It's great, I implemented the emojify method in my D.JS bot and it works perfectly, good job!

Thanks for the feedback connor! if you want to see any new methods/features, either open a pull request implementing the feature or opening an issue to request it so I can see if I can implement it, appreciate it.
